CREATE TABLE MAGICCARDS (
		ID INTEGER,
		NAME VARCHAR(80),
		COST VARCHAR(40),
		TYPE VARCHAR(80),
		POWER VARCHAR(10),
		TOUGHNESS VARCHAR(10),
		ORACLETEXT VARCHAR(1000),
		EDITION VARCHAR(80),
		RARITY VARCHAR(40),
		CLASS VARCHAR(40)
	);

